spring.application.name=gerenciador-faturas
# ----------------------------------------
# 1. Configuração de Conexão com o PostgreSQL
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/faturas_db
spring.datasource.username=postgres
spring.datasource.password=${SENHA_DB}

# ----------------------------------------
# 2. Configurações do Hibernate / JPA
# ----------------------------------------
# O "update" faz o Spring criar ou alterar as tabelas no banco automaticamente
spring.jpa.hibernate.ddl-auto=update

# O dialeto ajuda o Hibernate a traduzir o código Java para o SQL específico do Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ----------------------------------------
# 3. Logs no Console (Ótimo para debugar)
# ----------------------------------------
# Mostra no terminal do VS Code todo o SQL que o Spring está executando no banco
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true